name: joke_app
description: Simple joke app made in Flutter

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  ###
  # DEPENDENCIES
  ###
  alice: 0.2.5
  dio: 4.0.6
  flutter_screenutil: 5.5.4
  flutter_staggered_animations: 1.1.1
  get: 4.6.5
  google_fonts: 3.0.1
  hive: 2.2.3
  hive_flutter: 1.1.0
  logger_fork: 1.2.0
  logger_flutter_fork: 1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: 0.10.0
  flutter_native_splash: 2.2.8

  flutter_lints: ^2.0.0

# Configuration for 'flutter_launcher_icons'
# Run icon generation with 'flutter pub run flutter_launcher_icons:main'
flutter_icons:
  android: true
  ios: true
  image_path: 'assets/icons/jester_icon.png'
  adaptive_icon_background: 'assets/icons/jester_icon_background.png'
  adaptive_icon_foreground: 'assets/icons/jester_icon_foreground.png'

  # Configuration for 'flutter_native_splash'
  # Run splash screen generation with 'flutter pub run flutter_native_splash:create'
flutter_native_splash:
  android: true
  ios: true
  color: '#F29CB1'
  image: 'assets/icons/jester_icon.png'

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
